
name: Deploy Static HTML to EC2 with Docker and Nginx

on:
  push:
    branches:
      - qa  # Ejecuta solo en la rama qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Crear el archivo .pem desde el secreto
    - name: Create SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    # 3. Construir y subir la imagen Docker al registro
    - name: Build and Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t my-static-html .
        docker tag my-static-html:latest ${{ secrets.DOCKER_USERNAME }}/my-static-html:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-static-html:latest

    # 4. Configurar y desplegar en la primera instancia EC2
    - name: Setup and Deploy to EC2 QA1
      run: |
        ssh -i ec2_key.pem -o "StrictHostKeyChecking=no" \
          -o "UserKnownHostsFile=/dev/null" \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP_QA1 }} \
          "sudo yum update -y && \
           sudo yum install nginx -y && \
           sudo systemctl start nginx && \
           sudo systemctl enable nginx && \
           sudo chmod -R 755 /usr/share/nginx/html && \
           sudo chown -R ec2-user:ec2-user /usr/share/nginx/html && \
           docker pull ${{ secrets.DOCKER_USERNAME }}/my-static-html:latest && \
           docker stop static-html-container || true && \
           docker rm static-html-container || true && \
           docker run -d --name static-html-container -p 80:80 -v /usr/share/nginx/html:/usr/share/nginx/html nginx"

    # 5. Configurar y desplegar en la segunda instancia EC2
    - name: Setup and Deploy to EC2 QA2
      run: |
        ssh -i ec2_key.pem -o "StrictHostKeyChecking=no" \
          -o "UserKnownHostsFile=/dev/null" \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP_QA2 }} \
          "sudo yum update -y && \
           sudo yum install nginx -y && \
           sudo systemctl start nginx && \
           sudo systemctl enable nginx && \
           sudo chmod -R 755 /usr/share/nginx/html && \
           sudo chown -R ec2-user:ec2-user /usr/share/nginx/html && \
           docker pull ${{ secrets.DOCKER_USERNAME }}/my-static-html:latest && \
           docker stop static-html-container || true && \
           docker rm static-html-container || true && \
           docker run -d --name static-html-container -p 80:80 -v /usr/share/nginx/html:/usr/share/nginx/html nginx"

    # 6. Limpia el archivo de la clave
    - name: Clean up
      run: rm -f ec2_key.pem
